# Generated by Django 5.0.6 on 2024-06-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('allgemeinmedizin ', 'Allgemeinmedizin'), ('innere medizin', 'Innere Medizin'), ('chirurgie', 'Chirurgie'), ('anästhesiologie', 'Anästhesiologie'), ('gynäkologie', 'Gynäkologie'), ('pädiatrie', 'Pädiatrie'), ('psychatrie', 'Psychatrie'), ('radiologie', 'Radiologie')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='title',
            field=models.CharField(choices=[('dr', 'Dr.med.'), ('prof', 'Prof. Dr.med.'), ('pd', 'PD Dr.med.')], max_length=20),
        ),
    ]
