# Generated by Django 5.0.6 on 2024-06-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_doctorprofile_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Allgemeinmedizin ', 'Allgemeinmedizin'), ('Innere Medizin', 'Innere Medizin'), ('Chirurgie', 'Chirurgie'), ('Anästhesiologie', 'Anästhesiologie'), ('Gynäkologie', 'Gynäkologie'), ('Pädiatrie', 'Pädiatrie'), ('Psychatrie', 'Psychatrie'), ('Radiologie', 'Radiologie')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Dr.med.', 'Dr.med.'), ('Prof. Dr.med.', 'Prof. Dr.med.'), ('PD Dr.med.', 'PD Dr.med.')], max_length=20),
        ),
    ]
